spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
  profiles:
    active: dev
  main:
    allow-circular-references: true
  output:
    ansi:
      enabled: always

mybatis:
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true
  type-aliases-package: com.aptc.pojo
  mapper-locations: classpath:mapper/*.xml


server:
  port: 8080
  address: 0.0.0.0

ety:
  jwt:
    admin-secret-key: etyaptcetyaptcetyaptcetyaptcetyaptcetyaptcetyaptcetyaptc
    admin-ttl: 7200000
    admin-token-name: token
    user-secret-key: etyaptcetyaptcetyaptcetyaptcetyaptcetyaptcetyaptcetyaptc
    user-ttl: 7200000
    user-token-name: authentication