spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true

ety:
  jwt:
    admin-secret-key: etyaptcetyaptcetyaptcetyaptcetyaptcetyaptcetyaptcetyaptc
    admin-ttl: 7200000
    admin-token-name: token
    user-secret-key: etyaptcetyaptcetyaptcetyaptcetyaptcetyaptcetyaptcetyaptc
    user-ttl: 7200000
    user-token-name: authentication